#!/bin/bash
# A script by dehemi weerakkody ( @stargazer39 ) for bashaway2022
# Finds a Dockerfile in a folder and builds it, and runs it
# Aguments added to this script is sent to docker run command
# (last argument is sent to docker-find-build)
# Example that finds Dockerfile and runs interactivly -
# docker-find-run -it .
 
echo "Finding and building the docker container"
FILE_PATH=$(find ${@: -1} -name Dockerfile -print -quit  | xargs -I{} dirname {})
echo "Found a DockerFile on $FILE_PATH"
echo "Starting \"docker build -q $FILE_PATH\""

docker run "${@:1:$#-1}" $(docker build -q $FILE_PATH)
